#!/usr/bin/env bash

echo "This is push hook for project repo, version 1.1"
echo "$(pwd)"

cp ../../hooks/update_setup.sh ../../hooks/update_setup.sh.bak
wget https://raw.githubusercontent.com/ahpxue/public_test/main/project_setup/update_setup.sh

sh ../../hooks/update_setup.sh

exit 0

