#!/usr/bin/env bash

echo "This is push hook for project repo, version 1.1"
echo "$(pwd)"

wget https://raw.githubusercontent.com/ahpxue/public_test/main/project_setup/update_setup.sh  -O ./hooks/update_setup_new.sh

if diff ./hooks/update_setup_new.sh ./hooks/update_setup.sh >/dev/null; then
    rm ./hooks/update_setup_new.sh
else
    rm ./hooks/update_setup.sh
    mv ./hooks/update_setup_new.sh ./hooks/update_setup.sh
    echo "update_setup.sh is updated. Please push again"
    git add ./hooks/update_setup.sh
    git commit -m "Automatic commit: updating ./hooks/update_setup.sh"
    exit 1
fi

sh ./hooks/update_setup.sh

exit 0

